### ISSUE TITLE
Service hangs when filter string not found in log file

### ISSUE THREAD

**Issue by AndyNewmanCRIBL** [whargrove/qlog#1]
The service consumes a lot of CPU, and will hang if the filter query is not found.

To reproduce:

- echo "line one" > /var/log/smallfile
- curl -Ss "http://localhost:8080/queryLog?relativePath=smallfile&filter=WILLNOTFIND"

**Comment by AndyNewmanCRIBL** [comment]
or even easier step to reproduce

```
 curl -Ss "http://localhost:8080/queryLog?relativePath=syslog&filter=WILLNOTEVERFINDTHIS"
```

**Comment by whargrove** [comment]
😨 Indeed! There were some missing head of file conditions that caused this bug.

I've merged a PR that should address it.
